#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
ctags -Rf.git/tags.$$ --exclude=.git --exclude=node_modules --languages=-javascript,sql --tag-relative=yes
mv .git/tags.$$ .git/tags
