#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
if [ -z "$VIRTUAL_ENV" ]; then
    ctags -Rf.git/tags.$$ --exclude=.git --exclude=node_modules --languages=-javascript,sql --tag-relative=yes
else
    ctags -Rf.git/tags.$$ --exclude=.git --exclude=node_modules --languages=-javascript,sql $VIRTUAL_ENV
    ctags -Rf.git/tags.$$ --exclude=.git --exclude=node_modules --languages=-javascript,sql --tag-relative=yes --append=yes
fi
mv .git/tags.$$ .git/tags
