[tools]
awscli = "2.31.5"
aws-vault = "7.2.0"
chamber = "3.1.3"
golang = "1.25.1"
neovim = "0.11.4"
nodejs = "24.9.0"
python = "3.13.7"
rust = "1.90.0"

[settings]
experimental = true
python_compile = true
