[tools]
"npm:htmx-lsp" = "latest"
"npm:prettier" = "latest"
"npm:typescript-language-server" = "latest"
lua-language-server = "latest"
nodejs = "24.10.0"
python = "3.14.4"
rust = "latest"
stylua = "latest"
tree-sitter = "latest"
ty = "latest"
uv = "latest"

[settings]
experimental = true
