[tools]
awscli = 'latest'
aws-vault = '7.2.0'
chamber = '2.14.1'
golang = '1.23.0'
neovim = '0.11.3'
nodejs = '22.13.1'
python = '3.13.1'
rust = "latest"

[settings]
experimental = true
python_compile = true
