model:           bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0
weak-model:      bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
show-model-warnings: false
dark-mode: true
auto-commits: false
