model:           bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0
weak-model:      bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0
thinking-tokens: 32k
add-gitignore-files: true
auto-commits: false
dark-mode: true
