model:           litellm_proxy/claude-haiku-4-5
weak-model:      litellm_proxy/claude-haiku-3-5
thinking-tokens: 32k
add-gitignore-files: true
auto-commits: false
dark-mode: true
check-model-accepts-settings: false
show-model-warnings: false
