[tools]
shellcheck = "latest"
taplo = "latest"
yamlfmt = "latest"

[tasks.format]
description = "Format Lua, JSON, Markdown, TOML, and YAML files"
run = """
echo "Formatting JSON and Markdown files..."
prettier --write '**/*.json' '**/*.md'

echo "Formatting Lua files..."
find ./ -name '*.lua' -print0 | xargs -0 stylua

echo "Formatting TOML files..."
find ./ -name '*.toml' -not -path './.git/*' -print0 | xargs -0 taplo fmt

echo "Formatting YAML files..."
find ops/arch -name '*.yml' -print0 | xargs -0 yamlfmt

echo "Done!"
"""

[tasks.lint]
description = "Lint shell scripts"
run = """
echo "Linting shell scripts..."
find ./ -name 'tmux' -prune -o -name '*.sh' -print0 | xargs -0 shellcheck

echo "Done!"
"""
