[tools]
yamlfmt = "latest"
shellcheck = "latest"
stylua = "2.3.0"

[alias]
# specify a custom repo url
# note this will only be used if the plugin does not already exist
stylua = 'https://github.com/jc00ke/asdf-stylua'
