---

- name: Install rust cargo binaries
  become: true
  become_user: wamberg
  command: "zsh -ilc 'cargo install {{ item }}'"
  loop:
    - fd-find
    - git-delta
    - ripgrep

- name: Reshim asdf for cargo binaries
  become: true
  become_user: wamberg
  command: "zsh -ilc 'asdf reshim'"
