---
- name: CLI | Software | Basic | Install
  ansible.builtin.apt:
    state: latest
    cache_valid_time: 86400 # 1 day
    update_cache: yes
    pkg:
      - btop
      - build-essential
      - ca-certificates
      - curl
      - ffmpeg
      - fzf
      - git
      - gnupg
      - libnss3-tools
      - jq
      - locales
      - lsb-release
      - make
      - mkcert
      - stow
      - sudo
      - sqlite3
      - tmux
      - unzip
      - vifm
      - wget
      - xclip
      - zsh

- name: CLI | Software | Basic | Upgrade
  ansible.builtin.apt:
    upgrade: full

- name: CLI | Software | Basic | Remove Unused
  ansible.builtin.apt:
    autoremove: yes

# Set locale
- name: CLI | Locale | Ensure en_US-UTF-8
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: CLI | Locale | Set en_US-UTF-8 as default
  command: update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

- include_tasks: software/docker.yml
- include_tasks: wamberg.yml
- include_tasks: software/rtx.yml
- include_tasks: software/aws.yml
  #- include_tasks: software/cargo.yml
- include_tasks: software/neovim.yml
- include_tasks: software/tmux.yml
