---
- name: CLI | Users | wamberg | Add
  ansible.builtin.user:
    name: wamberg
    shell: /bin/zsh
    groups: sudo,docker
    append: yes

- name: CLI | Users | wamberg | Check for .zshrc
  stat:
    path: "/home/wamberg/.zshrc"
  register: zshrc_stat

- name: CLI | Users | wamberg | Install oh-my-zsh if needed
  when: not zshrc_stat.stat.exists
  block:
    - name: Install oh-my-zsh
      ansible.builtin.include_role:
        name: oh_my_zsh
      vars:
        users:
          - username: wamberg
            oh_my_zsh:
              install: true
              plugins:
                - asdf

    - name: Remove oh_my_zsh .zshrc
      ansible.builtin.file:
        path: /home/wamberg/.zshrc
        state: absent

- name: CLI | Users | wamberg | Stow dot_files
  become: true
  become_user: wamberg
  become_flags: "--login"
  command: 'stow --dir="${HOME}/dev/dot_files" --target="${HOME}/" -RS {{ item }}'
  loop:
    - bin
    - git
    - npm
    - nvim
    - rtx
    - tmux
    - vifm
    - zsh
