session_name: cli
windows:
- focus: 'true'
  layout: 9918,190x76,0,0[190x23,0,0{95x23,0,0,1,94x23,96,0,2},190x52,0,24,3]
  options:
    automatic-rename: 'off'
  panes:
  -
  -
  - focus: 'true'
  start_directory: $HOME/dev
  window_name: app
- layout:
  options:
    automatic-rename: 'off'
  panes:
  -
  - focus: 'true'
  start_directory: $HOME/dev/garden
  window_name: log
