session_name: cli
windows:
- layout: 0a39,114x27,0,0[114x8,0,0{57x8,0,0,0,56x8,58,0,2},114x18,0,9,1]
  focus: 'true'
  options: {}
  panes:
  -
  -
  - focus: 'true'
  start_directory: $HOME/dev
  window_name: app
- layout: 8aa0,114x27,0,0[114x8,0,0{57x8,0,0,3,56x8,58,0,5},114x18,0,9,4]
  options: {}
  panes:
  -
  -
  - shell_command:
    - cd garden
    - nvim index.wiki
    focus: 'true'
  start_directory: $HOME/dev
  window_name: log
