- hosts: localhost
  become: yes
  tasks:
    - name: Ensure cli packages are installed
      community.general.pacman:
        name:
          - base-devel
          - btop
          - ca-certificates
          - curl
          - ffmpeg
          - fzf
          - git
          - jq
          - sqlite
          - stow
          - sudo
          - tmux
          - unzip
          - vifm
          - wget
          - xclip
          - zsh
        state: present
      tags:
        - cli
    - name: System | Upgrade all packages
      community.general.pacman:
        update_cache: yes
        upgrade: yes
      tags:
        - upgrade
    - name: System | Check for orphaned packages
      ansible.builtin.command:
        cmd: pacman -Qtdq
      register: orphans
      changed_when: false
      failed_when: false
      tags:
        - upgrade
    - name: System | Remove orphaned packages
      community.general.pacman:
        name: "{{ orphans.stdout_lines }}"
        state: absent
      when: orphans.stdout != ""
      tags:
        - upgrade
    - name: Create aur_builder user
      ansible.builtin.user:
        name: aur_builder
        state: present
        create_home: yes
        system: yes
      tags:
        - aur_setup
        - aur
    - name: Grant aur_builder passwordless sudo for pacman
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-aur_builder
        state: present
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        owner: root
        group: root
        mode: '0440'
        validate: 'visudo -cf %s'
      tags:
        - aur_setup
        - aur
    - name: Create Ansible temporary directory for aur_builder
      ansible.builtin.file:
        path: /home/aur_builder/.ansible/tmp
        state: directory
        owner: aur_builder
        group: aur_builder
        mode: '0700'
      tags:
        - aur_setup
        - aur
    - name: Ensure yay is installed
      kewlfft.aur.aur:
        name: yay
      become: yes
      become_user: aur_builder # NOTE: This user must be pre-configured with passwordless sudo
      tags:
        - aur
