- hosts: localhost
  become: yes
  tasks:
    - name: System | Packages | Ensure CLI tools are installed
      community.general.pacman:
        update_cache: yes
        name:
          - base-devel
          - bat
          - btop
          - ca-certificates
          - curl
          - ffmpeg
          - fzf
          - git
          - jq
          - mise
          - sqlite
          - stow
          - sudo
          - tmux
          - unzip
          - vifm
          - wget
          - xclip
          - zsh
        state: present
      tags:
        - cli
    - name: System | Packages | Ensure Docker is installed
      community.general.pacman:
        update_cache: yes
        name:
          - docker
          - docker-compose
        state: present
      tags:
        - dev
    - name: Service | Docker | Enable and start service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
      tags:
        - dev
    - name: User | wamberg | Set shell to zsh and add to docker, wheel groups
      ansible.builtin.user:
        name: wamberg
        shell: /bin/zsh
        groups: docker,wheel
        append: yes
      tags:
        - dev
    - name: User | wamberg | Check for .zshrc
      ansible.builtin.stat:
        path: "/home/wamberg/.zshrc"
      register: zshrc_stat
      become: yes
      become_user: wamberg
      tags:
        - dev
    - name: User | wamberg | Install oh-my-zsh if needed
      when: not zshrc_stat.stat.exists
      become: yes
      become_user: wamberg
      tags:
        - dev
      block:
        - name: User | wamberg | Install oh-my-zsh
          ansible.builtin.shell:
            cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
            creates: /home/wamberg/.oh-my-zsh
        - name: User | wamberg | Remove oh-my-zsh .zshrc
          ansible.builtin.file:
            path: /home/wamberg/.zshrc
            state: absent
    - name: User | wamberg | Stow dot_files
      become: yes
      become_user: wamberg
      become_flags: "--login"
      ansible.builtin.shell: 'stow --dir="${HOME}/dev/dot_files" --target="${HOME}/" -vS {{ item }}'
      loop:
        - aider
        - bat
        - bin
        - claude
        - git
        - glow
        - kitty
        - mise
        - niri
        - npm
        - nvim
        - sql
        - tmux
        - vifm
        - zsh
      register: stow_result
      changed_when: stow_result.stdout != ""
      tags:
        - dev
    - name: User | wamberg | Check for missing mise tools
      become: yes
      become_user: wamberg
      become_flags: "--login"
      ansible.builtin.shell: 'mise ls --missing'
      register: mise_missing
      changed_when: false
      tags:
        - dev
    - name: User | wamberg | Install mise tools
      become: yes
      become_user: wamberg
      become_flags: "--login"
      ansible.builtin.shell: 'mise install'
      when: mise_missing.stdout != ""
      tags:
        - dev
    - name: User | tmux | Ensure plugins directory exists
      become: yes
      become_user: wamberg
      ansible.builtin.file:
        path: /home/wamberg/.tmux/plugins
        state: directory
        mode: '0755'
        force: yes
      tags:
        - dev
    - name: User | tmux | Check if tpm is already installed
      become: yes
      become_user: wamberg
      ansible.builtin.stat:
        path: /home/wamberg/.tmux/plugins/tpm/.git
      register: tpm_git_stat
      tags:
        - dev
    - name: User | tmux | Clone plugin manager (tpm)
      become: yes
      become_user: wamberg
      ansible.builtin.git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "/home/wamberg/.tmux/plugins/tpm"
        depth: 1
      when: not tpm_git_stat.stat.exists
      tags:
        - dev
    - name: System | Upgrade all packages
      community.general.pacman:
        update_cache: yes
        upgrade: yes
      tags:
        - upgrade
    - name: System | Check for orphaned packages
      ansible.builtin.command:
        cmd: pacman -Qtdq
      register: orphans
      changed_when: false
      failed_when: false
      tags:
        - upgrade
    - name: System | Remove orphaned packages
      community.general.pacman:
        name: "{{ orphans.stdout_lines }}"
        state: absent
      when: orphans.stdout != ""
      tags:
        - upgrade
    - name: User | aur_builder | Create user
      ansible.builtin.user:
        name: aur_builder
        state: present
        create_home: yes
        system: yes
      tags:
        - aur_setup
        - aur
    - name: User | aur_builder | Grant passwordless sudo for pacman
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-aur_builder
        state: present
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        owner: root
        group: root
        mode: '0440'
        validate: 'visudo -cf %s'
      tags:
        - aur_setup
        - aur
    - name: User | aur_builder | Create Ansible temporary directory
      ansible.builtin.file:
        path: /home/aur_builder/.ansible/tmp
        state: directory
        owner: aur_builder
        group: aur_builder
        mode: '0700'
      tags:
        - aur_setup
        - aur
    - name: System | Packages | Ensure yay is installed
      kewlfft.aur.aur:
        name: yay
        update_cache: yes
      become: yes
      become_user: aur_builder # NOTE: This user must be pre-configured with passwordless sudo
      tags:
        - aur
    - name: System | Packages | Install niri compositor
      kewlfft.aur.aur:
        name: niri
        update_cache: yes
      become: yes
      become_user: aur_builder
      tags:
        - desktop
    - name: System | Packages | Install essential desktop packages
      community.general.pacman:
        name:
          # Terminal emulator
          - kitty

          # Status bar and launcher
          - waybar
          - fuzzel

          # Notifications and system utilities
          - mako
          - playerctl

          # Screenshots and clipboard
          - grim
          - slurp
          - wl-clipboard

          # Screen locking
          - swaylock

          # Optional: Virtual filesystem support
          - gvfs

          # Audio system
          - pipewire
          - pipewire-alsa
          - pipewire-pulse
          - wireplumber
          - pavucontrol

          # Fonts
          - ttf-firacode-nerd
          - noto-fonts-emoji

          # Optional: Basic icon theme
          - adwaita-icon-theme

          # Display manager
          - sddm

        state: present
      tags:
        - desktop
    - name: Service | SDDM | Enable display manager
      ansible.builtin.systemd:
        name: sddm
        enabled: no
      tags:
        - desktop
    - name: Service | PipeWire | Enable user services
      become: yes
      become_user: wamberg
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
        scope: user
      loop:
        - pipewire.service
        - pipewire-pulse.service
        - wireplumber.service
      tags:
        - desktop
