- hosts: localhost
  become: yes
  tasks:
    - name: Ensure cli packages are installed
      community.general.pacman:
        name:
          - base-devel
          - bat
          - btop
          - ca-certificates
          - curl
          - ffmpeg
          - fzf
          - git
          - jq
          - mise
          - sqlite
          - stow
          - sudo
          - tmux
          - unzip
          - vifm
          - wget
          - xclip
          - zsh
        state: present
      tags:
        - cli
    - name: Ensure docker packages are installed
      community.general.pacman:
        update_cache: yes
        name:
          - docker
          - docker-compose
        state: present
      tags:
        - dev
    - name: Ensure docker service is enabled and running
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
      tags:
        - dev
    - name: User | wamberg | Set shell to zsh and add to docker, wheel groups
      ansible.builtin.user:
        name: wamberg
        shell: /bin/zsh
        groups: docker,wheel
        append: yes
      tags:
        - wamberg
    - name: User | wamberg | Check for .zshrc
      ansible.builtin.stat:
        path: "/home/wamberg/.zshrc"
      register: zshrc_stat
      become: yes
      become_user: wamberg
      tags:
        - wamberg
    - name: User | wamberg | Install oh-my-zsh if needed
      when: not zshrc_stat.stat.exists
      become: yes
      become_user: wamberg
      tags:
        - wamberg
      block:
        - name: Install oh-my-zsh
          ansible.builtin.shell:
            cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
            creates: /home/wamberg/.oh-my-zsh
        - name: Remove oh_my_zsh .zshrc
          ansible.builtin.file:
            path: /home/wamberg/.zshrc
            state: absent
    - name: User | wamberg | Stow dot_files
      become: yes
      become_user: wamberg
      become_flags: "--login"
      ansible.builtin.shell: 'stow --dir="${HOME}/dev/dot_files" --target="${HOME}/" -RS {{ item }}'
      loop:
        - aider
        - bat
        - bin
        - claude
        - git
        - glow
        - kitty
        - mise
        - npm
        - nvim
        - sql
        - tmux
        - vifm
        - zsh
      tags:
        - wamberg
    - name: System | Upgrade all packages
      community.general.pacman:
        update_cache: yes
        upgrade: yes
      tags:
        - upgrade
    - name: System | Check for orphaned packages
      ansible.builtin.command:
        cmd: pacman -Qtdq
      register: orphans
      changed_when: false
      failed_when: false
      tags:
        - upgrade
    - name: System | Remove orphaned packages
      community.general.pacman:
        name: "{{ orphans.stdout_lines }}"
        state: absent
      when: orphans.stdout != ""
      tags:
        - upgrade
    - name: Create aur_builder user
      ansible.builtin.user:
        name: aur_builder
        state: present
        create_home: yes
        system: yes
      tags:
        - aur_setup
        - aur
    - name: Grant aur_builder passwordless sudo for pacman
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-aur_builder
        state: present
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        owner: root
        group: root
        mode: '0440'
        validate: 'visudo -cf %s'
      tags:
        - aur_setup
        - aur
    - name: Create Ansible temporary directory for aur_builder
      ansible.builtin.file:
        path: /home/aur_builder/.ansible/tmp
        state: directory
        owner: aur_builder
        group: aur_builder
        mode: '0700'
      tags:
        - aur_setup
        - aur
    - name: Ensure yay is installed
      kewlfft.aur.aur:
        name: yay
      become: yes
      become_user: aur_builder # NOTE: This user must be pre-configured with passwordless sudo
      tags:
        - aur
