---
- name: Install Python dependencies
  ansible.builtin.apt:
    state: latest
    cache_valid_time: 86400 # 1day
    update_cache: yes
    pkg:
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxmlsec1-dev
      - llvm
      - tk-dev
      - xz-utils
      - zlib1g-dev

- name: Install asdf languages
  ansible.builtin.include_role:
    name: asdf
  vars:
    asdf_user: wamberg
    asdf_group: wamberg
    asdf_plugins:
    - name: "python"
      versions:
        - "{{ python_version }}"
      global: "{{ python_version }}"
    - name: "nodejs"
      versions:
        - "{{ nodejs_version }}"
      global: "{{ nodejs_version }}"
    - name: "rust"
      versions:
        - "{{ rust_version }}"
      global: "{{ rust_version }}"
    - name: "awscli"
      versions:
        - "{{ awscli_version }}"
      global: "{{ awscli_version }}"
