---

- name: CLI | Software | Cargo | Install binstall
  become: true
  become_user: wamberg
  command: "zsh -ilc 'cargo install cargo-binstall'"

- name: CLI | Software | Cargo | Install Cargo Binaries
  become: true
  become_user: wamberg
  command: "zsh -ilc 'cargo binstall {{ item }}'"
  loop:
    - fd-find
    - git-delta
    - ripgrep
