---
- name: Software | LunarVim | Check
  stat:
    path: "/home/wamberg/.local/bin/lvim"
  register: lvim_stat

- name: Software | LunarVim | Clone if needed
  when: not lvim_stat.stat.exists
  block:
    - name: Software | LunarVim | Create LunarVim directory
      file:
        path: /opt/lvim
        state: directory
        owner: wamberg
        group: wamberg
        mode: 0775

    - name: Software | LunarVim | Clone
      become: true
      become_user: wamberg
      ansible.builtin.git:
        repo: "https://github.com/LunarVim/LunarVim.git"
        dest: "/opt/lvim"
        depth: 1
