---
- name: CLI | Software | rtx | Install Python dependencies
  ansible.builtin.apt:
    state: latest
    cache_valid_time: 86400 # 1 day
    update_cache: yes
    pkg:
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxmlsec1-dev
      - llvm
      - tk-dev
      - xz-utils
      - zlib1g-dev

- name: CLI | Software | rtx | Install rtx
  ansible.builtin.get_url:
    url: "https://github.com/jdxcode/rtx/releases/download/{{ rtx_version }}/rtx-{{ rtx_version }}-linux-x64"
    dest: "/usr/bin/rtx"
    mode: "0755"

- name: CLI | Software | rtx | wamberg owns rtx
  file:
    path: "/usr/bin/rtx"
    state: file
    owner: wamberg
    group: wamberg
    mode: 0755

- name: CLI | Software | rtx | rtx install
  become: true
  become_user: wamberg
  command: "zsh -ilc 'rtx install'"
